// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// enumerate_configs
Rcpp::List enumerate_configs(arma::vec& z0, arma::mat& ld, double prior_variance, int d, double thresh);
RcppExport SEXP _BTS_enumerate_configs(SEXP z0SEXP, SEXP ldSEXP, SEXP prior_varianceSEXP, SEXP dSEXP, SEXP threshSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type z0(z0SEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type ld(ldSEXP);
    Rcpp::traits::input_parameter< double >::type prior_variance(prior_varianceSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< double >::type thresh(threshSEXP);
    rcpp_result_gen = Rcpp::wrap(enumerate_configs(z0, ld, prior_variance, d, thresh));
    return rcpp_result_gen;
END_RCPP
}
// compute_post_locus
Rcpp::List compute_post_locus(List locus_configs, arma::vec& enrich0, arma::mat& locus_annot);
RcppExport SEXP _BTS_compute_post_locus(SEXP locus_configsSEXP, SEXP enrich0SEXP, SEXP locus_annotSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type locus_configs(locus_configsSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type enrich0(enrich0SEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type locus_annot(locus_annotSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_post_locus(locus_configs, enrich0, locus_annot));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BTS_enumerate_configs", (DL_FUNC) &_BTS_enumerate_configs, 5},
    {"_BTS_compute_post_locus", (DL_FUNC) &_BTS_compute_post_locus, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_BTS(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
